version: 2.1
executors:
  cci-java11:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      MAVEN_OPTS: -Xmx3G
aliases:
  ### Application version
  - &get-version-git-tag
    name: Getting app version from git-tag
    command: |
      currentVersion=$(git describe --tags --abbrev=0 | cut -d'-' -f2)
      nextVersionPatchNumber=$(($(echo $currentVersion | grep -o '[0-9]*$')+1))
      staticVersion=$(echo $currentVersion | grep -o '[0-9].[0-9].')
      echo release-$staticVersion$nextVersionPatchNumber
      APP_VERSION=release-$staticVersion$nextVersionPatchNumber
      echo "export APP_VERSION=$APP_VERSION" >> $BASH_ENV
      echo $APP_VERSION > ./app_versio

  - &save-test-results
    name: Save test results
    command: |
      mkdir -p ~/reports/{junit,owasp}
      find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/reports/junit/ \;
      find . -type f -regex ".*/target/owasp-reports/.*" -exec cp {} ~/reports/owasp/ \;

    when: always

  - &post_build
    name: Trigger downstream builds
    command: |
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      chmod u+x .circleci/trigger_build_v2.sh
      .circleci/trigger_build_v2.sh "entur/otp-deployment-config.git" "otp-1" "$(git log -1 --pretty=%B)"

jobs:
  test:
    executor: cci-java11
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/m2/settings.xml -O .circleci/settings.xml
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn test -s .circleci/settings.xml
      - run: *save-test-results
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  build:
    executor: cci-java11
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/m2/settings.xml -O .circleci/settings.xml
      - run: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/trigger_build_v2.sh -O .circleci/trigger_build_v2.sh
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: *get-version-git-tag
      - run: mvn deploy -s .circleci/settings.xml -DskipTests
      - run: *post_build

workflows:
  release:
    jobs:
      - test:
          name: test-release
          context: global
      - build:
          name: build-release
          context: global
          filters:
            branches:
              only:
                - rutebanken_develop
          requires:
            - test-release