version: 2.1

orbs:
  helm: entur/helm@0.0.1
  slack: circleci/slack@2.2.0
  clair: ovotech/clair-scanner@1.4.25
  docker: circleci/docker-publish@0.1.6

executors:
  java-11:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          _JAVA_OPTIONS: -Xmx1024m
          TERM: dumb
          TZ: "/usr/share/zoneinfo/Europe/Stockholm"
  entur-cci-toolbox:
    docker:
      - image: entur/cci-toolbox:2.0
  cci-toolbox-java11:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image-java11
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      DEBIAN_FRONTEND: "noninteractive"
aliases:
  ### Application version

  - &get-version-from-helm-values
    name: Getting app version from helm-value version
    command: |
      appversion=$(cat ./helm/OpenTripPlanner/values.yaml | grep "appVersion" | cut -d':' -f2)
      echo "export APP_VERSION=$appversion" >> $BASH_ENV

  - &set-versions-to-app-version
    name: Set version in helm dir to $APP_VERSION
    command: |
      echo "Setting helm versions to $APP_VERSION"
      pushd helm/$CIRCLE_PROJECT_REPONAME
      sed -i "s/version:.*$/version: '$APP_VERSION'/g"  ./Chart.yaml
      sed -i "s/appVersion:.*$/appVersion: 'release-$APP_VERSION'/g"  ./Chart.yaml
      sed -i "s/imageTag:.*$/imageTag: release-$APP_VERSION/g"  ./values.yaml
      popd
  - &GCP-auth
    name: GCP Authentication for Google Cloud Deploy
    command: |
      echo $GCLOUD_SERVICE_KEY > ${HOME}/account-auth.json
      gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
      gcloud --quiet container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER

  - &docker-login
    name: Login with docker on gcloud
    command: docker login -u _json_key -p "${GCLOUD_SERVICE_KEY}" https://eu.gcr.io
  - &bump-versions
    name: Bump version in pom file
    command: |
      echo "Bumping versions from $APP_VERSION to $NEXTVERSION"
      sed -i "s/appVersion=.*$/appVersion=$NEXTVERSION/g" ./helm/OpenTripPlanner/values.yaml
      pushd helm/$CIRCLE_PROJECT_REPONAME
      sed -i "s/version:.*$/version: '$NEXTVERSION'/g"  ./Chart.yaml
      sed -i "s/appVersion:.*$/appVersion: 'release-$NEXTVERSION'/g"  ./Chart.yaml
      sed -i "s/imageTag:.*$/imageTag: release-$NEXTVERSION/g"  ./values.yaml
      popd

  - &git-push-next-version-release
    name: Push to repository
    command: |
      echo "Trying to tag release-$MVN_VERSION"
      git config --global user.email "circleci@entur.org"
      git config --global user.name "EnturCircleCi"
      git tag -a release-$MVN_VERSION -m "Tagging current version"
      git add helm/$CIRCLE_PROJECT_REPONAME/Chart.yaml
      git add helm/$CIRCLE_PROJECT_REPONAME/values.yaml
      git add pom.xml
      git commit -m "Helm Update [ci skip]"
      git push --tags --set-upstream origin $CIRCLE_BRANCH

    ### Application version handling
  - &tag-successful-deployment
    name:
    command: |
      echo "Trying to tag successful deployment with: $NAMESPACE-$MVN_VERSION"
      tag=release-$MVN_VERSION
      gitcommit=$(git rev-list -n 1 $tag)
      git config --global user.email "circleci@entur.org"
      git config --global user.name "EnturCircleCi"
      git tag -a $NAMESPACE-$MVN_VERSION $gitcommit -m "Tagging successfull deployment of version $MVN_VERSION to $NAMESPACE"
      git push origin $NAMESPACE-$MVN_VERSION

  - &team-ror-circleci-slackhook
      https://hooks.slack.com/services/${SLACK_API_KEY_CIRCLE_CI}

  - &team-ror-releases-slackhook
      https://hooks.slack.com/services/${SLACK_API_KEY_RELEASES}

  # Use the parameter CONDITIONAL_SLACKHOOK to customize where the message gets sent
  - &team-ror-conditional-slackhook
      https://hooks.slack.com/services/${CONDITIONAL_SLACKHOOK}

  - &save-test-results
    name: Save test results
    command: |
      mkdir -p ~/reports/{junit,owasp}
      find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/reports/junit/ \;
      find . -type f -regex ".*/target/owasp-reports/.*" -exec cp {} ~/reports/owasp/ \;

    when: always

  - &deploy-payload
      "*Ready to Deploy*: <$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_REPONAME #$CIRCLE_PREVIOUS_BUILD_NUM> to *$NAMESPACE*\n
        Repository: <https://circleci.com/bb/enturas/workflows/$CIRCLE_PROJECT_REPONAME|$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME>\n
        Branch: <https://circleci.com/bb/enturas/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH|$CIRCLE_BRANCH>\n
        Version: $MVN_VERSION \n
        User: $CIRCLE_USERNAME"

  - &success-payload
      ":tada: Job $CIRCLE_STAGE has succeeded!\n
         Version: $MVN_VERSION \n
         User: $CIRCLE_USERNAME"

  - &failure-payload
      ":red_circle: Job $CIRCLE_STAGE has failed!\n
         Version: $MVN_VERSION \n
         User: $CIRCLE_USERNAME"


commands:
  slack-status:
    parameters:
      success_payload:
        type: string
        default: *success-payload
    steps:
      - attach_workspace:
          at: .
      - run: *get-version-from-helm-values
      - slack/status:
          webhook: *team-ror-circleci-slackhook
          success_message: << parameters.success_payload >>
          failure_message: *failure-payload
  save-image-name:
    parameters:
      image-version:
        type: string
        default: $BRANCH_IMAGE_NAME-SNAPSHOT
    steps:
      - run:
          command: echo "$DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:<< parameters.image-version >>" > ./gcr.image.version
      - persist_to_workspace:
          root: .
          paths: ./gcr.image.version
jobs:
  build:
    executor: cci-toolbox-java11
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: *get-version-from-helm-values
      - run: mvn deploy -s /tools/m2/settings.xml
      - run: *save-test-results
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
      - persist_to_workspace:
          root: ~/project
          paths:
            - target
            - pom.xml
            - .circleci
            - helm/*/
            - ./mvn_version
      - slack-status
  prepare-next-release:
    executor: cci-toolbox-java11

    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run: *get-version-from-helm-values
      - run: *bump-versions
      - run: *git-push-next-version-release
      - slack-status

  deploy:
    executor: entur-cci-toolbox

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: *GCP-auth
      - helm/install-helm-chart:
          chart: ./helm/$CIRCLE_PROJECT_REPONAME
          namespace: $NAMESPACE
          release-name: $CIRCLE_PROJECT_REPONAME
      - run:
          name: Deployed helm chart
          command: cat ./helm/$CIRCLE_PROJECT_REPONAME/Chart.yaml
      - run: *get-version-from-helm-values
      - run: *GCP-auth
      - helm/install-helm-chart:
          chart: ./helm/$CIRCLE_PROJECT_REPONAME
          namespace: $NAMESPACE
          release-name: $CIRCLE_PROJECT_REPONAME-$BRANCH_IMAGE_NAME-$NAMESPACE
      - run:
          name: Deployed helm chart
          command: cat ./helm/$CIRCLE_PROJECT_REPONAME/Chart.yaml
      - run: *tag-successful-deployment

      - slack-status

  slack-approval:
    executor: slack/alpine
    steps:
      - attach_workspace:
          at: .
      - run: *get-version-from-helm-values
      - slack/approval:
          webhook: *team-ror-releases-slackhook
          message: *deploy-payload


workflows:
  version: 2.1
  release:
    jobs:
      - build:
          name: build-release
          context: dev
      - docker/publish:
          name: push-release
          registry: $DOCKER_REGISTRY
          image: $CIRCLE_PROJECT_REPONAME
          tag: release-$GRADLE_VERSION
          deploy: true
          context: global
          requires:
            - build-release
          after_checkout:
            - attach_workspace:
                at: .
            - run: *get-version-from-helm-values
          post-steps:
            - save-image-name:
                image-version: release-$APP_VERSION
            - slack-status
      - prepare-next-release:
          requires:
            - push-release
      - deploy:
          name: deploy-dev-release
          context: dev
          requires:
                - prepare-next-release