{{- if .Values.cronjobRedeployGraphBuilder.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
    name: graph-builder
    namespace: {{ .Release.Namespace }}
data:
  build-config.json: |+
      {
        "htmlAnnotations": true,
        // Changed from false
        "transit": true,
        "useTransfersTxt": false,
        "parentStopLinking": true,
        // Changed from false
        "stationTransfers": false,
        "subwayAccessTime": 0,
        // Changed from 2.0
        "streets": true,
        "embedRouterConfig": true,
        "areaVisibility": true,
        "platformEntriesLinking": true,
        // Changed from true
        "matchBusRoutesToStreets": false,
        "fetchElevationUS": false,
        "osmWayPropertySet": "norway",
        // Changed from default
        "staticBikeRental": false,
        "staticParkAndRide": false,
        "staticBikeParkAndRide": false,
        "maxHtmlAnnotationsPerFile": 1000,
        "maxInterlineDistance": 200,
        "allowDuplicateStops": false,
        "islandWithoutStopsMaxSize": 5,
        // Changed from 40
        "islandWithStopsMaxSize": 5,
        "banDiscouragedWalking": false,
        "banDiscouragedBiking": false,
        "maxTransferDistance": 2000,
        "extraEdgesStopPlatformLink": true,
        // Changed from false
        "stopClusterMode": "parentStation",
        "netex": {
          "sharedFilePattern": "_stops.xml",
          "sharedGroupFilePattern": "_(\\w{3})(_flexible)?_shared_data.xml",
          "groupFilePattern": "(\\w{3})_.*\\.xml",
          "netexFeedId": "RB",
          "flexMaxTravelTime": "2t+5",
          "defaultMinimumFlexPaddingTime": 15
        },
        "storage" : {
          "gsCredentials": "/etc/marduk/marduk-blobstore-credentials.json",
          "osm" : ["gs://{{ .Values.mardukBucket }}/osm/norway-latest.osm.pbf"],
          "dem" : ["gs://{{ .Values.mardukBucket }}/kartverket/heightData/norge_dem_50m_33.tif"],
          "netex": ["gs://{{ .Values.mardukBucket }}/outbound/netex/rb_norway-aggregated-netex.zip"],
          "baseGraph": "gs://{{ .Values.mardukBucket }}/${OTP_GCS_BASE_GRAPH_DIR}/baseGraph.obj",
          "graph": "gs://{{ .Values.mardukBucket }}/${OTP_GCS_WORK_DIR}/Graph.obj",
          "buildReportDir": "gs://{{ .Values.mardukBucket }}/${OTP_GCS_WORK_DIR}/report",
          "otpStatusDir": "gs://{{ .Values.mardukBucket }}/${OTP_GCS_WORK_DIR}"
        },
        "linkMultiModalStopsToParentStations": true,
        "parkAndRideFromTransitData": true,
        "callAndRideReluctance": 2,
        "analyzeTransfers": true,
        "distanceBetweenElevationSamples": 25
      }
{{end}}