apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    name: otp
  name: otp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: otp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: otp
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - otp
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - command:
            - /docker-entrypoint.sh
            - java
            - -Dfile.encoding=UTF-8
            - -Dtransmodel.graphql.api.agency.id=RB
            - -Xms10g
            - -Xmx12g
            - -server
            - -Dcom.sun.management.jmxremote
            - -Dcom.sun.management.jmxremote.port=9010
            - -Dcom.sun.management.jmxremote.local.only=false
            - -Dcom.sun.management.jmxremote.authenticate=false
            - -Dcom.sun.management.jmxremote.ssl=false
            - -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{`{{host=0.0.0.0}}`}},jmx_exporter{{`{{9779:/opt/agent-bond/jmx_exporter_config.yml}}`}}
            - -jar
            - otp-shaded.jar
            - --server
            - --graphs
            - /code/otpdata
            - --router
            - norway
          env:
            - name: TZ
              value: Europe/Oslo
            - name: MARDUK_GCP_BASE
              value: gs://marduk/
            - name: ROUTER_CONFIG
              value: router-config.json
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '10'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /otp/routers/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 900
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: otp
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /otp/routers/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          resources:
            limits:
              cpu: '7'
              memory: 15000Mi
            requests:
              cpu: '2'
              memory: 13100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/marduk/
              name: marduk-key
            - mountPath: /code/otpdata/norway/router-config.json
              name: config-volume
              subPath: router-config.json
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: rutebanken-registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31
      volumes:
        - name: marduk-key
          secret:
            defaultMode: 420
            secretName: marduk-carbon-storage-key
        - configMap:
            defaultMode: 420
            name: otp-router-config
          name: config-volume
