{{- if .Values.cronjobRedeployOtp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-redeploy-{{ template "otp.name" . }}
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-redeploy-{{ template "otp.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-redeploy-{{ template "otp.name" . }}
subjects:
- kind: ServiceAccount
  name: cronjob-redeploy-{{ template "otp.name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-redeploy-{{ template "otp.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}