apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ template "otp.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: otp
      port: {{ .Values.service.otp.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.otp.nternalPort }}
  selector:
    app: {{ template "otp.name" . }}
  sessionAffinity: None
  type: ClusterIP

